# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run : echo "Hello world from Testing"


  my_deploy:
    runs-on: ubuntu-latest
    needs  : [my_testing]
    
    steps:
      - name: Print Hello Message
        run : echo "Hello world from Deploy"
    
